-- =====================================================================
-- 99_resume.sql — Réveil du pipeline (avant une démo)
-- Inverse de 99_pause.sql. Pense à relancer le consumer ensuite.
-- =====================================================================
USE ROLE CRYPTO_PIPELINE_ROLE;

-- Historique (Dynamic Table ; FCT_OHLCV_1MIN est INCREMENTAL, rafraichi par dbt build)
ALTER DYNAMIC TABLE IF EXISTS ANALYTICS.PUBLIC_MARTS.FCT_ORDERBOOK_SNAPSHOTS RESUME;

-- Monitoring (Alert + Tasks)
ALTER ALERT IF EXISTS ANALYTICS.MONITORING.CRYPTO_FRESHNESS_ALERT    RESUME;
ALTER TASK  IF EXISTS ANALYTICS.MONITORING.CRYPTO_DBT_TEST           RESUME;
ALTER TASK  IF EXISTS ANALYTICS.MONITORING.CRYPTO_SCHEMA_DRIFT_CHECK RESUME;
ALTER TASK  IF EXISTS ANALYTICS.MONITORING.CRYPTO_QUALITY_CHECK      RESUME;
-- Surveillance ML (07) + retention (08)
ALTER TASK  IF EXISTS ANALYTICS.MONITORING.CRYPTO_ANOMALY_RETRAIN    RESUME;
ALTER TASK  IF EXISTS ANALYTICS.MONITORING.CRYPTO_ANOMALY_SCORE      RESUME;
ALTER ALERT IF EXISTS ANALYTICS.MONITORING.CRYPTO_ANOMALY_ALERT      RESUME;
ALTER TASK  IF EXISTS ANALYTICS.MONITORING.CRYPTO_RAW_RETENTION      RESUME;

-- Vérification
SHOW TASKS          IN SCHEMA ANALYTICS.MONITORING;
SHOW ALERTS         IN SCHEMA ANALYTICS.MONITORING;
SHOW DYNAMIC TABLES IN SCHEMA ANALYTICS.PUBLIC_MARTS;

-- Puis, sur ton Mac, relance l'ingestion :
--   cd ~/Documents/snowflake/ingestion && source venv/bin/activate && python stream_to_snowflake.py
